# GoReleaser configuration for Engram
# Documentation: https://goreleaser.com
version: 2

project_name: engram

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: engram
    main: ./cmd/engram
    binary: engram
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.Date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

# Docker images
dockers:
  - id: amd64
    image_templates:
      - "ghcr.io/hyperengineering/engram:{{ .Tag }}-amd64"
      - "ghcr.io/hyperengineering/engram:v{{ .Major }}-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
    dockerfile: Dockerfile.goreleaser

  - id: arm64
    image_templates:
      - "ghcr.io/hyperengineering/engram:{{ .Tag }}-arm64"
      - "ghcr.io/hyperengineering/engram:v{{ .Major }}-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
    dockerfile: Dockerfile.goreleaser

docker_manifests:
  - name_template: "ghcr.io/hyperengineering/engram:{{ .Tag }}"
    image_templates:
      - "ghcr.io/hyperengineering/engram:{{ .Tag }}-amd64"
      - "ghcr.io/hyperengineering/engram:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/hyperengineering/engram:v{{ .Major }}"
    image_templates:
      - "ghcr.io/hyperengineering/engram:v{{ .Major }}-amd64"
      - "ghcr.io/hyperengineering/engram:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/hyperengineering/engram:latest"
    image_templates:
      - "ghcr.io/hyperengineering/engram:{{ .Tag }}-amd64"
      - "ghcr.io/hyperengineering/engram:{{ .Tag }}-arm64"

# Homebrew tap
brews:
  - name: engram
    repository:
      owner: hyperengineering
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/hyperengineering/engram"
    description: "Centralized lore persistence and synchronization service"
    license: "MIT"
    extra_install: |
      # Install wrapper script
      (bin/"engram-wrapper").write <<~EOS
        #!/bin/bash
        set -e
        ENV_FILE="#{etc}/engram/environment"
        if [[ -f "$ENV_FILE" ]]; then
          set -a
          source "$ENV_FILE"
          set +a
        fi
        exec "#{bin}/engram" "$@"
      EOS
      (bin/"engram-wrapper").chmod 0755

      # Create config directory and environment template
      (etc/"engram").mkpath
      (var/"engram").mkpath
      (var/"log/engram").mkpath

      # Install environment template (don't overwrite existing)
      unless (etc/"engram/environment").exist?
        (etc/"engram/environment").write <<~EOS
          # Engram Environment Variables
          # Permissions: 600 (chmod 600 #{etc}/engram/environment)

          # Required: API key for authenticating clients
          # Generate: openssl rand -hex 32
          ENGRAM_API_KEY=

          # Required: OpenAI API key for embedding generation
          # Get from: https://platform.openai.com/api-keys
          OPENAI_API_KEY=

          # Optional: Override default port (8080)
          # ENGRAM_PORT=8080

          # Optional: Override default host (localhost)
          # ENGRAM_HOST=0.0.0.0
        EOS
        (etc/"engram/environment").chmod 0600
      end
    install: |
      bin.install "engram"
    service: |
      run [opt_bin/"engram-wrapper"]
      working_dir var/"engram"
      log_path var/"log/engram/engram.log"
      error_log_path var/"log/engram/engram.log"
      keep_alive true
    caveats: |
      To complete setup:

        1. Configure your API keys:
           nano #{etc}/engram/environment

           Set ENGRAM_API_KEY and OPENAI_API_KEY

        2. Start the service:
           brew services start engram

        3. Verify it's running:
           curl http://localhost:8080/api/v1/health

      Configuration: #{etc}/engram/environment
      Data:          #{var}/engram/
      Logs:          #{var}/log/engram/engram.log
    test: |
      system "#{bin}/engram", "version"

# System packages (deb/rpm)
nfpms:
  - id: packages
    package_name: engram
    vendor: Hyperengineering
    maintainer: Engram Team <engram@hyperengineering.dev>
    description: "Centralized lore persistence and synchronization service"
    license: MIT
    homepage: "https://github.com/hyperengineering/engram"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: packaging/engram.yaml
        dst: /etc/engram/engram.yaml
        type: config|noreplace
      - src: packaging/environment
        dst: /etc/engram/environment
        type: config|noreplace
      - src: packaging/engram.service
        dst: /usr/lib/systemd/system/engram.service
      # Data directory (owned by engram user)
      - dst: /var/lib/engram
        type: dir
        file_info:
          owner: engram
          group: engram
          mode: 0750
    scripts:
      preinstall: packaging/scripts/preinstall.sh
      postinstall: packaging/scripts/postinstall.sh
    overrides:
      deb:
        dependencies:
          - systemd
      rpm:
        dependencies:
          - systemd

# Publish deb/rpm to Gemfury
publishers:
  - name: fury.io
    ids:
      - packages
    cmd: >-
      curl -sf -F p1=@{{ .ArtifactPath }}
      https://{{ .Env.FURY_PUSH_TOKEN }}@push.fury.io/neuralmux/
    extra_files:
      - glob: ""

release:
  github:
    owner: hyperengineering
    name: engram
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
